// ============================================================
//  HeartPathIndex — LilithsHeart
//  LilithsHeart/Config/HeartPathIndex.cs
//
//  Single source of truth for every filesystem path used by
//  LilithsHeart and its child modules.
//
//  All config for the entire suite lives under one root:
//      BepInEx/config/LilithsHeart/
//
//  Structure:
//      LilithsHeart/
//          LilithsHeart.cfg            ← Heart core settings
//          LilithsCookbook.cfg         ← child module cfg files
//          Aliases/                    ← per-server prefab name alias overrides
//              WeaponsIndex.json
//              StationsIndex.json
//              ItemsResourcesIndex.json
//              PrisonerFeedIndex.json
//              ... one file per *Index class
//          Items/                      ← item overrides (appearance + functional)
//              ItemExamples.json
//              CookbookItemExamples.json
//          Recipes/                    ← recipe config (LilithsCookbook)
//              RecipeExamples.json
//              PrisonerFeedExamples.json
//              PrisonerFedExamples.json
//              AllRecipes.json (on demand)
//          MainQuest/                  ← quest text (LilithsMachinations, future)
//          Spells/                     ← spell names/tooltips (LilithsGrimoire, future)
//
//  [CHANGED] AliasesDir added — per-server prefab name alias overrides.
//            One JSON file per *Index class. Scanned by PrefabNameResolver
//            after compiled defaults are loaded. Admins edit these files
//            to use custom aliases in all module configs on this server.
//            Generated by PrefabNameResolver when GenerateNameAliasConfigs
//            is set in LilithsHeart.cfg.
// ============================================================

namespace LilithsHeart.Config;

public static class HeartPathIndex
{
    // ── Root ────────────────────────────────────────────────

    /// <summary>
    /// BepInEx/config/LilithsHeart/
    /// All suite config lives under this directory.
    /// </summary>
    public static readonly string Root = Path.Combine(
        BepInEx.Paths.ConfigPath,
        "LilithsHeart"
    );

    // ── .cfg files ──────────────────────────────────────────

    /// <summary>
    /// BepInEx/config/LilithsHeart/LilithsHeart.cfg
    /// </summary>
    public static readonly string CoreConfig = Path.Combine(Root, "LilithsHeart.cfg");

    /// <summary>
    /// Returns the path for a child module's .cfg file.
    /// e.g. HeartPathIndex.ModuleConfig("LilithsCookbook")
    ///      → BepInEx/config/LilithsHeart/LilithsCookbook.cfg
    /// </summary>
    public static string ModuleConfig(string moduleName)
        => Path.Combine(Root, $"{moduleName}.cfg");

    // ── Data subdirectories ─────────────────────────────────

    /// <summary>
    /// BepInEx/config/LilithsHeart/Aliases/
    /// Per-server prefab name alias overrides. One JSON file per
    /// LilithsMind *Index class (e.g. WeaponsIndex.json).
    /// Each file maps prefab string → custom alias name.
    /// Loaded by PrefabNameResolver after compiled defaults.
    /// Admin aliases take priority over compiled Name fields.
    /// Prefab strings are always preserved as a fallback.
    ///
    /// [CHANGED] Added for the name alias system.
    /// </summary>
    public static readonly string AliasesDir = Path.Combine(Root, "Aliases");

    /// <summary>
    /// BepInEx/config/LilithsHeart/Items/
    /// All item override files — appearance and functional.
    /// Scanned recursively by ItemService. Admins can create
    /// subdirectories freely (e.g. Items/Currencies/, Items/Weapons/).
    /// </summary>
    public static readonly string ItemsDir = Path.Combine(Root, "Items");

    /// <summary>
    /// BepInEx/config/LilithsHeart/Localization/
    /// Per-language item name and description overrides.
    /// One subfolder per language — name must match LanguageCodeEnum exactly
    /// (e.g. Localization/Spanish/, Localization/SChinese/).
    /// Each subfolder scanned recursively for *.json files.
    /// Loaded by LocalizationFileService at world ready.
    ///
    /// [CHANGED] Added for multi-language localization support.
    /// </summary>
    public static readonly string LocalizationDir = Path.Combine(Root, "Localization");

    /// <summary>
    /// Returns the path for a named data subdirectory.
    /// e.g. HeartPathIndex.DataDir("Recipes")
    ///      → BepInEx/config/LilithsHeart/Recipes/
    ///
    /// The directory is NOT created here — call Directory.CreateDirectory()
    /// at the point of first use.
    /// </summary>
    public static string DataDir(string category)
        => Path.Combine(Root, category);
}